"""Blake's Hotel as data: the guide's steps, the gates, and the room graph."""

import state

# The speedrun.com guide list, GetGuideList?gameId=k6q4gw0d, guide y45ls
# "Blake's Hotel algorithm 2023-02-10": 116 numbered lines, quoted in
# `source` exactly as the guide writes them.
GUIDE = "speedrun.com guide y45ls, Blake's Hotel algorithm 2023-02-10"

LOBBY = 16
OFFICE = 17
HALLWAY = 9
CAFE = 13
GARDENER = 14

# Every room the walk reached, by the word at 0x6ac. The names are the
# banners the game draws; a room a step 1 run never entered has no number.
ROOM_WORD = {"lobby": LOBBY, "office": OFFICE, "hallway": HALLWAY,
             "cafe": CAFE, "gardener": GARDENER}

# Which held direction leaves which room, what it reaches, and what has to
# be open first. Measured on the emulator; a room not listed was not
# reached by step 1.
EDGES = (("lobby", "up", "hallway", None),
         ("lobby", "down", "cafe", None),
         ("lobby", "right", "office", "lobby door"),
         ("hallway", "left", "lobby", None),
         ("hallway", "up", "gardener", "door #1"),
         ("gardener", "right", "hallway", None),
         ("cafe", "right", "lobby", None))

# A door is clicked, not walked through: the click walks Shaggy to it and
# the verb runs where he ends up.
DOORS = (("lobby", "Door", 44, (141, 48), "office"),
         ("hallway", "Door", 74, (47, 76), "door #1"),
         ("hallway", "Door", 75, (69, 68), "door #2"),
         ("hallway", "Door", 76, (85, 60), "door #3"),
         ("hallway", "Door", 81, (115, 56), "door #4"),
         ("hallway", "Door", 77, (143, 64), "door #5"),
         ("hallway", "Door", 78, (157, 64), "door #6"),
         ("hallway", "Door", 79, (183, 76), "door #7"))

# Hotspot centres read off the status line by rastering the crosshair, at
# the scroll each room settles at: the lobby and the cafe do not scroll,
# and the hallway's camera clamps right for every Shaggy x above 250.
SPOTS = {
    "lobby": {"Picture": (185, 44), "Zebra": (17, 100), "Mailbox": (229, 60),
              "Fire": (15, 60), "Bell": (165, 80), "Door": (141, 48),
              "Archway": (169, 152), "Stairs": (103, 44)},
    "hallway": {"Dumb Waiter": (7, 72), "The Stairs": (41, 128)},
    "gardener": {"Television": (209, 140), "Antenna": (199, 88),
                 "Air Freshener": (195, 124), "Door": (229, 88),
                 "Drawer": (171, 108), "Poison Oak": (33, 108),
                 "Bed Spring": (145, 96)},
    "cafe": {"Cash Register": (48, 100), "Key": (56, 68), "The Cook": (80, 28),
             "Double Doors": (112, 52), "Lamp": (144, 20), "Radio": (144, 60),
             "Scooby": (168, 76), "Archway": (192, 60),
             "Bottle of Oil": (192, 108), "Cabinet": (232, 100)},
}

# The hovered-object word, which says which of several hotspots of one name
# the crosshair rests on; the hallway's seven doors all read "Door".
HOVER = {"lobby": {"Picture": 37, "Zebra": 38, "Mailbox": 39, "Fire": 40,
                   "Bell": 43, "Door": 44, "Archway": 45, "Stairs": 46},
         "hallway": {"Dumb Waiter": 80, "The Stairs": 82},
         "gardener": {"Television": 83, "Antenna": 84, "Air Freshener": 85,
                      "Door": 86, "Drawer": 88, "Poison Oak": 89,
                      "Bed Spring": 90}}

WALK = "walk"
ACT = "act"

# Shaggy's own word, 0x4dc, is walked to this before a hallway step, so the
# camera is at its right clamp and the centres above hold.
HALL_ANCHOR = None


def step(number, room, kind, source, verb=None, obj=None, hover=None,
         centre=None, edge=None, anchor=None, gate=None, yields=None,
         every=False):
    """One line of the guide, with everything the player needs to run it."""
    return {"n": number, "room": room, "kind": kind, "verb": verb,
            "object": obj, "hover": hover, "centre": centre, "edge": edge,
            "anchor": anchor, "gate": gate, "yields": yields,
            "every": every, "source": source}


STEPS = (
    step(1, "lobby", WALK, "Goto Hallway", edge="up"),
    step(2, "hallway", ACT, "Click Door #1", verb=state.OPEN, obj="Door",
         hover=74, centre=(47, 76), anchor=HALL_ANCHOR, yields="door #1"),
    step(3, "hallway", ACT, "Click Door #2", verb=state.OPEN, obj="Door",
         hover=75, centre=(69, 68), anchor=HALL_ANCHOR, yields="door #2"),
    step(4, "hallway", ACT, "Click Door #3", verb=state.OPEN, obj="Door",
         hover=76, centre=(85, 60), anchor=HALL_ANCHOR, yields="door #3"),
    step(5, "hallway", ACT, "Click Door #7", verb=state.OPEN, obj="Door",
         hover=79, centre=(183, 76), anchor=HALL_ANCHOR, yields="door #7"),
    step(6, "hallway", ACT, "Click Door #5", verb=state.OPEN, obj="Door",
         hover=77, centre=(143, 64), anchor=HALL_ANCHOR, yields="door #5"),
    step(7, "hallway", ACT, "Click Door #6", verb=state.OPEN, obj="Door",
         hover=78, centre=(157, 64), anchor=HALL_ANCHOR, yields="door #6"),
    step(8, "hallway", WALK, "Goto Gardener's Room", edge="up",
         gate="door #1"),
    step(9, "gardener", ACT, "Click both Bedside Tables", verb=state.OPEN,
         obj="Drawer", every=True, yields="bedside tables"),
    step(10, "gardener", ACT, "Take Antacid", verb=state.TAKE, obj="Antacid",
         gate="bedside tables", yields="antacid"),
    step(11, "gardener", WALK, "Goto Hallway", edge="right"),
    step(12, "hallway", ACT, "Click Dumb Waiter (CLONK)", verb=state.OPEN,
         obj="Dumb Waiter", hover=80, centre=(7, 72), anchor=HALL_ANCHOR,
         yields="kitchen"),
    step(13, "kitchen", ACT, "Push Refrigerator", verb=state.PUSH,
         obj="Refrigerator"),
    step(14, "kitchen", ACT, "Take Soda Tab", verb=state.TAKE, obj="Soda Tab",
         gate="refrigerator", yields="soda tab"),
    step(15, "kitchen", ACT, "Use Pot with Kitchen Sink", verb=state.USE,
         obj="Kitchen Sink", yields="pot of water"),
    step(16, "kitchen", ACT, "Click Microwave", verb=state.OPEN,
         obj="Microwave"),
    step(17, "kitchen", ACT, "Take Chili", verb=state.TAKE, obj="Chili",
         yields="chili"),
    step(18, "kitchen", ACT, "Push Flour", verb=state.PUSH, obj="Flour"),
    step(19, "kitchen", ACT, "Click Peephole", verb=state.LOOK,
         obj="Peephole", gate="flour", yields="the note appears"),
    step(20, "kitchen", WALK, "Goto Cafe", edge="down"),
    step(21, "cafe", ACT, "Push Radio", verb=state.PUSH, obj="Radio",
         centre=(144, 60)),
    step(22, "cafe", ACT, "Open Radio", verb=state.OPEN, obj="Radio",
         centre=(144, 60), gate="radio pushed"),
    step(23, "cafe", ACT, "Take Battery", verb=state.TAKE, obj="Battery",
         gate="radio open", yields="battery"),
    step(24, "cafe", ACT, "Eat Antacid (CLONK)", verb=state.EAT,
         obj="Antacid", gate="antacid", yields="the cook leaves"),
    step(25, "cafe", ACT, "Take Key", verb=state.TAKE, obj="Key",
         centre=(56, 68), gate="the cook leaves", yields="key"),
    step(26, "cafe", ACT, "Click Cabinet", verb=state.OPEN, obj="Cabinet",
         centre=(232, 100), yields="can opener"),
    step(27, "cafe", ACT, "Use Can Opener with Chili", verb=state.USE,
         obj="Chili", gate="can opener", yields="empty chili can"),
    step(28, "cafe", WALK, "Goto Lobby", edge="right"),
    step(29, "lobby", ACT, "Use Pot o' Water with Fire", verb=state.USE,
         obj="Fire", hover=40, centre=(15, 60), gate="pot of water",
         yields="the fire is out"),
    step(30, "lobby", ACT, "Take Crumpled Note", verb=state.TAKE,
         obj="Crumpled Note", gate="the fire is out", yields="crumpled note"),
    step(31, "lobby", ACT, "Click Outside Door", verb=state.OPEN,
         obj="Double Doors", yields="outside"),
    step(32, "lobby", WALK, "Goto Outside the Hotel (Left)", edge="left",
         gate="outside"),
    step(33, "outside-left", ACT, "Use Shovel with Snowman", verb=state.USE,
         obj="Snowman", yields="frozen bell"),
    step(34, "outside-left", ACT, "Use Key with Lock", verb=state.USE,
         obj="Lock", gate="key", yields="the shed"),
    step(35, "outside-left", ACT, "Click Door", verb=state.OPEN, obj="Door",
         gate="the shed"),
    step(36, "outside-left", ACT, "Take Crowbar", verb=state.TAKE,
         obj="Crowbar", gate="the shed", yields="crowbar"),
    step(37, "outside-left", ACT, "Take Gloves", verb=state.TAKE,
         obj="Work Gloves", gate="the shed", yields="work gloves"),
    step(38, "outside-left", ACT, "Take Weed Killer", verb=state.TAKE,
         obj="Weed Killer", gate="the shed", yields="weed killer"),
    step(39, "outside-left", ACT, "Take Frozen Bell", verb=state.TAKE,
         obj="Frozen Bell", gate="frozen bell", yields="frozen bell"),
    step(40, "outside-left", WALK, "Go Right", edge="right"),
    step(41, "outside-right", ACT, "Use Shovel with Covered Doors",
         verb=state.USE, obj="Snow Covered Doors"),
    step(42, "outside-right", ACT, "Use Crowbar with Locked Doors",
         verb=state.USE, obj="Locked Doors", gate="crowbar"),
    step(43, "outside-right", ACT, "Click Double Doors (CLONK)",
         verb=state.OPEN, obj="Double Doors", yields="the basement"),
    step(44, "outside-right", WALK, "Goto Basement", edge="down",
         gate="the basement"),
    step(45, "basement", ACT, "Use Crumpled note with Rack", verb=state.USE,
         obj="Rack", gate="the note looked at", yields="the mine"),
    step(46, "basement", ACT, "Click Locker", verb=state.OPEN, obj="Locker"),
    step(47, "basement", ACT, "Take Extension Cord", verb=state.TAKE,
         obj="Extension Cord", gate="locker", yields="extension cord"),
    step(48, "basement", ACT, "Take Screwdriver", verb=state.TAKE,
         obj="Screwdriver", gate="locker", yields="screwdriver"),
    step(49, "basement", WALK, "Goto Office", edge="up"),
    step(50, "office", ACT, "Take Heater", verb=state.TAKE, obj="Heater",
         yields="heater"),
    step(51, "office", ACT, "Click Drawer", verb=state.OPEN, obj="Drawer"),
    step(52, "office", ACT, "Take Scissors", verb=state.TAKE, obj="Scissors",
         gate="drawer", yields="scissors"),
    step(53, "office", ACT, "Click Door", verb=state.OPEN, obj="Door"),
    step(54, "office", WALK, "Goto Lobby", edge="left"),
    step(55, "lobby", WALK, "Goto Hallway", edge="up"),
    step(56, "hallway", WALK, "Goto Gardener's Room", edge="up",
         gate="door #1"),
    step(57, "gardener", ACT, "Take Book", verb=state.TAKE, obj="Book",
         yields="book"),
    step(58, "gardener", ACT, "Use Work Gloves with Poison Oak",
         verb=state.USE, obj="Poison Oak", hover=89, centre=(33, 108),
         gate="work gloves", yields="poison oak"),
    step(59, "gardener", ACT, "Take Bed Spring", verb=state.TAKE,
         obj="Bed Spring", hover=90, centre=(145, 96),
         yields="bed spring"),
    step(60, "gardener", ACT, "Take Air Freshener", verb=state.TAKE,
         obj="Air Freshener", hover=85, centre=(195, 124),
         yields="air freshener"),
    step(61, "gardener", WALK, "Goto Hallway", edge="down"),
    step(62, "hallway", ACT, "Click Dumb Waiter", verb=state.OPEN,
         obj="Dumb Waiter", hover=80, centre=(7, 72), anchor=HALL_ANCHOR),
    step(63, "kitchen", ACT, "Use Frozen Bell with Microwave",
         verb=state.USE, obj="Microwave", gate="frozen bell"),
    step(64, "kitchen", ACT, "Use Microwave", verb=state.USE,
         obj="Microwave"),
    step(65, "kitchen", ACT, "Click Microwave", verb=state.OPEN,
         obj="Microwave"),
    step(66, "kitchen", ACT, "Take Cow Bell", verb=state.TAKE,
         obj="Cow Bell", yields="cow bell"),
    step(67, "kitchen", ACT, "Use Screwdriver with Vent Cover",
         verb=state.USE, obj="Vent Cover", gate="screwdriver"),
    step(68, "kitchen", ACT, "Use Empty Chili Can with Termites",
         verb=state.USE, obj="Termites", gate="empty chili can",
         yields="termites"),
    step(69, "kitchen", WALK, "Goto Cafe", edge="down"),
    step(70, "cafe", WALK, "Goto Lobby", edge="right"),
    step(71, "lobby", ACT, "Use Extension Cord with Outlet", verb=state.USE,
         obj="Outlet", gate="extension cord"),
    step(72, "lobby", ACT, "Use Heater with Extension Cord", verb=state.USE,
         obj="Extension Cord", gate="heater"),
    step(73, "lobby", ACT, "Use Poison Oak with Bear", verb=state.USE,
         obj="Bear", gate="poison oak", yields="the bridge falls"),
    step(74, "lobby", WALK, "Goto Across the River (CLONK)", edge="left",
         gate="the bridge falls"),
    step(75, "bridge", ACT, "Use Pole (x3)", verb=state.USE, obj="Pole"),
    step(76, "bridge", ACT, "Use Scissors with Rope", verb=state.USE,
         obj="Rope", gate="scissors"),
    step(77, "bridge", ACT, "Take Rope", verb=state.TAKE, obj="Rope",
         yields="rope"),
    step(78, "bridge", ACT, "Take Doll", verb=state.TAKE, obj="Doll",
         yields="doll"),
    step(79, "bridge", WALK, "Goto Outside the Hotel", edge="right"),
    step(80, "outside-left", ACT, "Use Bed Spring", verb=state.USE,
         obj="Bed Spring", gate="bed spring"),
    step(81, "outside-left", ACT, "Take Christmas Lights", verb=state.TAKE,
         obj="Christmas Lights", yields="christmas lights"),
    step(82, "outside-left", WALK, "Goto Lobby", edge="right"),
    step(83, "lobby", ACT, "Use Cow Bell", verb=state.USE, obj="Cow Bell",
         gate="cow bell"),
    step(84, "lobby", ACT, "Give Doll to Bellhop", verb=state.GIVE,
         obj="Bellhop", gate="doll"),
    step(85, "lobby", ACT, "Take Goblet (CLONK)", verb=state.TAKE,
         obj="Goblet", yields="goblet"),
    step(86, "lobby", WALK, "Goto Office", edge="right"),
    step(87, "office", WALK, "Goto Basement", edge="down"),
    step(88, "basement", WALK, "Goto Mine", edge="left", gate="the mine"),
    step(89, "mine", ACT, "Take Wheel (x3)", verb=state.TAKE, obj="Wheel",
         yields="wheels"),
    step(90, "mine", ACT, "Use Wheels with Mine Car", verb=state.USE,
         obj="Mine Car", gate="wheels"),
    step(91, "mine", ACT, "Use Mine Car", verb=state.USE, obj="Mine Car",
         yields="the shaft"),
    step(92, "shaft", ACT, "Use Hose with Engine", verb=state.USE,
         obj="Engine"),
    step(93, "shaft", ACT, "Use Hose with Gas", verb=state.USE, obj="Gas"),
    step(94, "shaft", WALK, "Goto Pond", edge="left"),
    step(95, "pond", ACT, "Use Air Freshener", verb=state.USE,
         obj="Air Freshener", gate="air freshener"),
    step(96, "pond", WALK, "Goto Maze", edge="left"),
    step(97, "maze", ACT, "Use Battery with Soda Tab", verb=state.USE,
         obj="Soda Tab", gate="battery"),
    step(98, "maze", ACT,
         "Use Soda Tab and Battery with Christmas Light", verb=state.USE,
         obj="Christmas Lights", gate="christmas lights",
         yields="flashlight"),
    step(99, "maze", ACT, "Use Flashlight", verb=state.USE,
         obj="Flashlight",
         gate="flashlight"),
    step(100, "maze", WALK, "Goto Tomb (up left right left left right)",
         edge="up"),
    step(101, "tomb", ACT, "Use Goblet with Statue", verb=state.USE,
         obj="Statue", gate="goblet"),
    step(102, "tomb", ACT, "Use Weed Killer with Lettuce", verb=state.USE,
         obj="Killer Lettuce", gate="weed killer"),
    step(103, "tomb", WALK, "Goto Dungeon", edge="left"),
    step(104, "dungeon", ACT, "Use Rope with Cuffs", verb=state.USE,
         obj="Cuffs", gate="rope"),
    step(105, "dungeon", ACT, "Use Rope", verb=state.USE, obj="Rope"),
    step(106, "dungeon", ACT, "Use Termites with Uncle Blake",
         verb=state.USE, obj="Uncle Blake", gate="termites",
         yields="Blake freed"),
    step(107, "dungeon", WALK, "Goto Tomb", edge="right"),
    step(108, "tomb", ACT, "Give Book to Uncle Blake", verb=state.GIVE,
         obj="Uncle Blake", gate="book"),
    step(109, "tomb", ACT, "Talk to Statue (answer 4)", verb=state.TALK,
         obj="Statue"),
    step(110, "tomb", ACT, "Take Medallion", verb=state.TAKE,
         obj="Medallion", yields="medallion"),
    step(111, "tomb", WALK, "Goto Pond", edge="down"),
    step(112, "pond", ACT, "Click Switch", verb=state.PUSH, obj="Switch"),
    step(113, "pond", WALK, "Goto Mine", edge="right"),
    step(114, "mine", WALK, "Goto Basement", edge="right"),
    step(115, "basement", ACT, "Use Medallion with Hook", verb=state.USE,
         obj="Hook", gate="medallion", yields="the scenario ends"),
    step(116, "basement", ACT, "(CLONK)", verb=None, obj=None),
)

# The dependency graph the search in step 3 orders under. Each line is
# "what has to be true" -> "what it makes true"; the guide's own order is
# one topological sort of it.
DEPENDS = (
    ("antacid", "the antacid eaten"),
    ("the antacid eaten", "the cook leaves"),
    ("the cook leaves", "key"),
    ("key", "the shed"),
    ("the shed", "crowbar"),
    ("the shed", "work gloves"),
    ("the shed", "weed killer"),
    ("crowbar", "the basement"),
    ("the basement", "the mine car"),
    ("the mine car", "the shaft"),
    ("the shaft", "the maze"),
    ("flour", "the peephole"),
    ("the peephole", "crumpled note"),
    ("crumpled note", "the note looked at"),
    ("the note looked at", "the mine"),
    ("work gloves", "poison oak"),
    ("poison oak", "the bridge falls"),
    ("the bridge falls", "doll"),
    ("doll", "goblet"),
    ("goblet", "the statue"),
    ("screwdriver", "the vent"),
    ("the vent", "termites"),
    ("empty chili can", "termites"),
    ("termites", "Blake freed"),
    ("book", "Blake freed"),
    ("Blake freed", "the statue"),
    ("the statue", "medallion"),
    ("medallion", "the scenario ends"),
    ("battery", "flashlight"),
    ("soda tab", "flashlight"),
    ("christmas lights", "flashlight"),
    ("flashlight", "the maze walked"),
    ("pot of water", "the fire is out"),
    ("the fire is out", "crumpled note"),
)

# Two orders that lose the scenario, named so a search never proposes them.
SOFT_LOCKS = (
    ("the crumpled note", "taken but never looked at, the wine rack refuses"
     " it and the mine is unreachable"),
    ("the antacid", "the key is taken before the cook leaves, and the cook"
     " never leaves without the antacid eaten"),
)
